"""initial create auction_sales table

Revision ID: 4257ea2f8bf3
Revises: b58fe265b89d
Create Date: 2025-12-18 13:23:12.107139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4257ea2f8bf3'
down_revision: Union[str, Sequence[str], None] = 'b58fe265b89d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_name', sa.String(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('sale_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auction_sales', schema='public')
    # ### end Alembic commands ###
