"""v2 data model: vehicles, sources, listings, benchmarks, alerts, reports, scrape_runs

Revision ID: 577a6294a50e
Revises: a711eacd04fd
Create Date: 2026-06-24 14:54:04.011705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '577a6294a50e'
down_revision: Union[str, Sequence[str], None] = 'a711eacd04fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('alert_type', sa.String(length=30), nullable=False),
    sa.Column('criteria_json', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('notification_channel', sa.String(length=20), nullable=True),
    sa.Column('last_triggered_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_alerts_id'), 'alerts', ['id'], unique=False, schema='public')
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('base_url', sa.String(length=500), nullable=True),
    sa.Column('scraper_class', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('scrape_frequency_minutes', sa.Integer(), nullable=True),
    sa.Column('last_scraped_at', sa.DateTime(), nullable=True),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_index(op.f('ix_public_sources_id'), 'sources', ['id'], unique=False, schema='public')
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('make', sa.String(length=100), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('generation', sa.String(length=100), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('country_of_origin', sa.String(length=50), nullable=True),
    sa.Column('segment', sa.String(length=50), nullable=True),
    sa.Column('body_style', sa.String(length=50), nullable=True),
    sa.Column('engine_type', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('make', 'model', 'generation', name='uq_vehicle_identity'),
    schema='public'
    )
    op.create_index(op.f('ix_public_vehicles_id'), 'vehicles', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_vehicles_make'), 'vehicles', ['make'], unique=False, schema='public')
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=500), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('listing_url', sa.Text(), nullable=False),
    sa.Column('listing_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('asking_price', sa.Float(), nullable=True),
    sa.Column('sale_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('price_gbp', sa.Float(), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('mileage', sa.Integer(), nullable=True),
    sa.Column('mileage_unit', sa.String(length=10), nullable=True),
    sa.Column('vin', sa.String(length=50), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('transmission', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('auction_end_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('undervaluation_score', sa.Float(), nullable=True),
    sa.Column('score_details', sa.JSON(), nullable=True),
    sa.Column('scored_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['public.sources.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['public.vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_source_external'),
    schema='public'
    )
    op.create_index('ix_listings_make_model_year', 'listings', ['make', 'model', 'year'], unique=False, schema='public')
    op.create_index('ix_listings_score', 'listings', ['undervaluation_score'], unique=False, schema='public', postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_public_listings_id'), 'listings', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_listings_source_id'), 'listings', ['source_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_listings_status'), 'listings', ['status'], unique=False, schema='public')
    op.create_index(op.f('ix_public_listings_vehicle_id'), 'listings', ['vehicle_id'], unique=False, schema='public')
    op.create_table('price_benchmarks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=7), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('min_price', sa.Float(), nullable=True),
    sa.Column('max_price', sa.Float(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('price_trend', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['public.vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id', 'period', 'currency', name='uq_benchmark_vehicle_period'),
    schema='public'
    )
    op.create_index(op.f('ix_public_price_benchmarks_id'), 'price_benchmarks', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_price_benchmarks_vehicle_id'), 'price_benchmarks', ['vehicle_id'], unique=False, schema='public')
    op.create_table('scrape_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('listings_found', sa.Integer(), nullable=True),
    sa.Column('listings_new', sa.Integer(), nullable=True),
    sa.Column('listings_updated', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['public.sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_scrape_runs_id'), 'scrape_runs', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_scrape_runs_source_id'), 'scrape_runs', ['source_id'], unique=False, schema='public')
    op.create_table('ai_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('listing_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['public.listings.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['public.vehicles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_ai_reports_id'), 'ai_reports', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_ai_reports_report_type'), 'ai_reports', ['report_type'], unique=False, schema='public')
    op.create_table('alert_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('triggered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('was_seen', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['alert_id'], ['public.alerts.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['public.listings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='public'
    )
    op.create_index(op.f('ix_public_alert_matches_alert_id'), 'alert_matches', ['alert_id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_alert_matches_id'), 'alert_matches', ['id'], unique=False, schema='public')
    op.create_index(op.f('ix_public_alert_matches_listing_id'), 'alert_matches', ['listing_id'], unique=False, schema='public')
    op.drop_index(op.f('ix_public_auction_sales_id'), table_name='auction_sales')
    op.drop_index(op.f('ix_public_auction_sales_make'), table_name='auction_sales')
    op.drop_table('auction_sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auction_sales',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('car_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('sale_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sale_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('vin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mileage', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('make', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('model', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('auction_sales_pkey'))
    )
    op.create_index(op.f('ix_public_auction_sales_make'), 'auction_sales', ['make'], unique=False)
    op.create_index(op.f('ix_public_auction_sales_id'), 'auction_sales', ['id'], unique=False)
    op.drop_index(op.f('ix_public_alert_matches_listing_id'), table_name='alert_matches', schema='public')
    op.drop_index(op.f('ix_public_alert_matches_id'), table_name='alert_matches', schema='public')
    op.drop_index(op.f('ix_public_alert_matches_alert_id'), table_name='alert_matches', schema='public')
    op.drop_table('alert_matches', schema='public')
    op.drop_index(op.f('ix_public_ai_reports_report_type'), table_name='ai_reports', schema='public')
    op.drop_index(op.f('ix_public_ai_reports_id'), table_name='ai_reports', schema='public')
    op.drop_table('ai_reports', schema='public')
    op.drop_index(op.f('ix_public_scrape_runs_source_id'), table_name='scrape_runs', schema='public')
    op.drop_index(op.f('ix_public_scrape_runs_id'), table_name='scrape_runs', schema='public')
    op.drop_table('scrape_runs', schema='public')
    op.drop_index(op.f('ix_public_price_benchmarks_vehicle_id'), table_name='price_benchmarks', schema='public')
    op.drop_index(op.f('ix_public_price_benchmarks_id'), table_name='price_benchmarks', schema='public')
    op.drop_table('price_benchmarks', schema='public')
    op.drop_index(op.f('ix_public_listings_vehicle_id'), table_name='listings', schema='public')
    op.drop_index(op.f('ix_public_listings_status'), table_name='listings', schema='public')
    op.drop_index(op.f('ix_public_listings_source_id'), table_name='listings', schema='public')
    op.drop_index(op.f('ix_public_listings_id'), table_name='listings', schema='public')
    op.drop_index('ix_listings_score', table_name='listings', schema='public', postgresql_nulls_not_distinct=False)
    op.drop_index('ix_listings_make_model_year', table_name='listings', schema='public')
    op.drop_table('listings', schema='public')
    op.drop_index(op.f('ix_public_vehicles_make'), table_name='vehicles', schema='public')
    op.drop_index(op.f('ix_public_vehicles_id'), table_name='vehicles', schema='public')
    op.drop_table('vehicles', schema='public')
    op.drop_index(op.f('ix_public_sources_id'), table_name='sources', schema='public')
    op.drop_table('sources', schema='public')
    op.drop_index(op.f('ix_public_alerts_id'), table_name='alerts', schema='public')
    op.drop_table('alerts', schema='public')
    # ### end Alembic commands ###
