"""add make and model columns

Revision ID: a711eacd04fd
Revises: e088d6966140
Create Date: 2026-02-09 11:43:37.162969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a711eacd04fd'
down_revision: Union[str, Sequence[str], None] = 'e088d6966140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_sales', sa.Column('make', sa.String(length=100), nullable=True))
    op.add_column('auction_sales', sa.Column('model', sa.String(length=200), nullable=True))
    op.create_index(op.f('ix_public_auction_sales_make'), 'auction_sales', ['make'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_auction_sales_make'), table_name='auction_sales', schema='public')
    op.drop_column('auction_sales', 'model')
    op.drop_column('auction_sales', 'make')
    # ### end Alembic commands ###
