"""add new columns to auction_sales

Revision ID: e088d6966140
Revises: 4257ea2f8bf3
Create Date: 2025-12-18 14:42:45.907391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e088d6966140'
down_revision: Union[str, Sequence[str], None] = '4257ea2f8bf3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_sales', sa.Column('vin', sa.String(), nullable=True))
    op.add_column('auction_sales', sa.Column('mileage', sa.Integer(), nullable=True))
    op.add_column('auction_sales', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('auction_sales', sa.Column('source', sa.String(), nullable=True))
    op.add_column('auction_sales', sa.Column('url', sa.Text(), nullable=True))
    op.alter_column('auction_sales', 'sale_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index(op.f('ix_public_auction_sales_id'), 'auction_sales', ['id'], unique=False, schema='public')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_public_auction_sales_id'), table_name='auction_sales', schema='public')
    op.alter_column('auction_sales', 'sale_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_column('auction_sales', 'url')
    op.drop_column('auction_sales', 'source')
    op.drop_column('auction_sales', 'year')
    op.drop_column('auction_sales', 'mileage')
    op.drop_column('auction_sales', 'vin')
    # ### end Alembic commands ###
